[package]
name = "smbcloud-wallet-constants"
version = "1.0.6"
edition = "2021"
description = "smbCloud Wallet Constants for NotWallet Crypto."
license = "MIT"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "smbcloud_wallet_constants"

[dependencies]
tsync = "2"
