[package]
name = "smbcloud-wallet-constants"
version = "0.1.0"
edition = "2021"
description = "Solana toolkit for Not Wallet"
license = "MIT"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "smbcloud_wallet_constants"

[dependencies]
tsync = "2"
